FROM php:fpm-alpine

COPY wait-for-it.sh /usr/bin/wait-for-it

RUN chmod +x /usr/bin/wait-for-it


RUN apk --update --no-cache add git rabbitmq-c-dev bash \
    && apk add --no-cache --update --virtual .phpize-deps $PHPIZE_DEPS \
    && pecl install -o -f amqp redis \
    && docker-php-ext-enable amqp redis \
    && apk del .phpize-deps \
&& docker-php-ext-install pdo_mysql sockets


#&& curl -sS https://get.symfony.com/cli/installer | bash \
#&& mv /root/.symfony/bin/symfony /usr/bin/symfony

COPY --from=composer /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

CMD composer install ; wait-for-it database:3306 -- bin/console doctrine:migrations:migrate ;  php-fpm 